language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libglib2.0-dev valac-0.18
script:
  - cmake .
  - make
