# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(CMAKE_COMMAND) -E cmake_progress_start /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/CMakeFiles /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/CMakeFiles/progress.marks
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f CMakeFiles/Makefile2 tests/lib/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f CMakeFiles/Makefile2 tests/lib/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f CMakeFiles/Makefile2 tests/lib/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f CMakeFiles/Makefile2 tests/lib/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
tests/lib/CMakeFiles/test-lib.dir/rule:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f CMakeFiles/Makefile2 tests/lib/CMakeFiles/test-lib.dir/rule
.PHONY : tests/lib/CMakeFiles/test-lib.dir/rule

# Convenience name for target.
test-lib: tests/lib/CMakeFiles/test-lib.dir/rule
.PHONY : test-lib

# fast build rule for target.
test-lib/fast:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f tests/lib/CMakeFiles/test-lib.dir/build.make tests/lib/CMakeFiles/test-lib.dir/build
.PHONY : test-lib/fast

assertion.o: assertion.c.o
.PHONY : assertion.o

# target to build an object file
assertion.c.o:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f tests/lib/CMakeFiles/test-lib.dir/build.make tests/lib/CMakeFiles/test-lib.dir/assertion.c.o
.PHONY : assertion.c.o

assertion.i: assertion.c.i
.PHONY : assertion.i

# target to preprocess a source file
assertion.c.i:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f tests/lib/CMakeFiles/test-lib.dir/build.make tests/lib/CMakeFiles/test-lib.dir/assertion.c.i
.PHONY : assertion.c.i

assertion.s: assertion.c.s
.PHONY : assertion.s

# target to generate assembly for a file
assertion.c.s:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f tests/lib/CMakeFiles/test-lib.dir/build.make tests/lib/CMakeFiles/test-lib.dir/assertion.c.s
.PHONY : assertion.c.s

testcase.o: testcase.c.o
.PHONY : testcase.o

# target to build an object file
testcase.c.o:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f tests/lib/CMakeFiles/test-lib.dir/build.make tests/lib/CMakeFiles/test-lib.dir/testcase.c.o
.PHONY : testcase.c.o

testcase.i: testcase.c.i
.PHONY : testcase.i

# target to preprocess a source file
testcase.c.i:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f tests/lib/CMakeFiles/test-lib.dir/build.make tests/lib/CMakeFiles/test-lib.dir/testcase.c.i
.PHONY : testcase.c.i

testcase.s: testcase.c.s
.PHONY : testcase.s

# target to generate assembly for a file
testcase.c.s:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(MAKE) -f tests/lib/CMakeFiles/test-lib.dir/build.make tests/lib/CMakeFiles/test-lib.dir/testcase.c.s
.PHONY : testcase.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test-lib"
	@echo "... assertion.o"
	@echo "... assertion.i"
	@echo "... assertion.s"
	@echo "... testcase.o"
	@echo "... testcase.i"
	@echo "... testcase.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

