# The set of languages for which implicit dependencies are needed:
SET(CMAKE_DEPENDS_LANGUAGES
  "C"
  )
# The set of files for implicit dependencies of each language:
SET(CMAKE_DEPENDS_CHECK_C
  "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/assertion.c" "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/test-lib.dir/assertion.c.o"
  "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/testcase.c" "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/test-lib.dir/testcase.c.o"
  )
SET(CMAKE_C_COMPILER_ID "GNU")

# Pairs of files generated by the same build rule.
SET(CMAKE_MULTIPLE_OUTPUT_PAIRS
  "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/../../lib/test-lib.h" "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/assertion.c"
  "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/../../lib/test-lib.vapi" "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/assertion.c"
  "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/../../lib/test-lib_internal.h" "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/assertion.c"
  "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/testcase.c" "/home/zylex/Dropbox/workspace/Vala/EntropiaLandAreaManager/tests/lib/assertion.c"
  )


# Targets to which this target links.
SET(CMAKE_TARGET_LINKED_INFO_FILES
  )

# The include file search paths:
SET(CMAKE_C_TARGET_INCLUDE_PATH
  "tests/lib"
  )
SET(CMAKE_CXX_TARGET_INCLUDE_PATH ${CMAKE_C_TARGET_INCLUDE_PATH})
SET(CMAKE_Fortran_TARGET_INCLUDE_PATH ${CMAKE_C_TARGET_INCLUDE_PATH})
SET(CMAKE_ASM_TARGET_INCLUDE_PATH ${CMAKE_C_TARGET_INCLUDE_PATH})
