/* valatest-testcase.c generated by valac 0.20.1, the Vala compiler
 * generated from valatest-testcase.vala, do not modify */

/*
 * taken from http://blog.remysaissy.com/2012/11/setting-up-unit-tests-in-vala-project.html
 * 
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define VALA_TEST_TYPE_TEST_CASE (vala_test_test_case_get_type ())
#define VALA_TEST_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TEST_TYPE_TEST_CASE, ValaTestTestCase))
#define VALA_TEST_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TEST_TYPE_TEST_CASE, ValaTestTestCaseClass))
#define VALA_TEST_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TEST_TYPE_TEST_CASE))
#define VALA_TEST_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TEST_TYPE_TEST_CASE))
#define VALA_TEST_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TEST_TYPE_TEST_CASE, ValaTestTestCaseClass))

typedef struct _ValaTestTestCase ValaTestTestCase;
typedef struct _ValaTestTestCaseClass ValaTestTestCaseClass;
typedef struct _ValaTestTestCasePrivate ValaTestTestCasePrivate;

#define VALA_TEST_TEST_CASE_TYPE_ADAPTOR (vala_test_test_case_adaptor_get_type ())
#define VALA_TEST_TEST_CASE_ADAPTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TEST_TEST_CASE_TYPE_ADAPTOR, ValaTestTestCaseAdaptor))
#define VALA_TEST_TEST_CASE_ADAPTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TEST_TEST_CASE_TYPE_ADAPTOR, ValaTestTestCaseAdaptorClass))
#define VALA_TEST_TEST_CASE_IS_ADAPTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TEST_TEST_CASE_TYPE_ADAPTOR))
#define VALA_TEST_TEST_CASE_IS_ADAPTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TEST_TEST_CASE_TYPE_ADAPTOR))
#define VALA_TEST_TEST_CASE_ADAPTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TEST_TEST_CASE_TYPE_ADAPTOR, ValaTestTestCaseAdaptorClass))

typedef struct _ValaTestTestCaseAdaptor ValaTestTestCaseAdaptor;
typedef struct _ValaTestTestCaseAdaptorClass ValaTestTestCaseAdaptorClass;
#define _vala_test_test_case_adaptor_unref0(var) ((var == NULL) ? NULL : (var = (vala_test_test_case_adaptor_unref (var), NULL)))
typedef struct _ValaTestTestCaseAdaptorPrivate ValaTestTestCaseAdaptorPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ValaTestTestCaseParamSpecAdaptor ValaTestTestCaseParamSpecAdaptor;

struct _ValaTestTestCase {
	GObject parent_instance;
	ValaTestTestCasePrivate * priv;
};

struct _ValaTestTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (ValaTestTestCase* self);
	void (*tear_down) (ValaTestTestCase* self);
};

struct _ValaTestTestCasePrivate {
	GTestSuite* suite;
	ValaTestTestCaseAdaptor** adaptors;
	gint adaptors_length1;
	gint _adaptors_size_;
};

typedef void (*ValaTestTestCaseTestMethod) (void* user_data);
struct _ValaTestTestCaseAdaptor {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValaTestTestCaseAdaptorPrivate * priv;
};

struct _ValaTestTestCaseAdaptorClass {
	GTypeClass parent_class;
	void (*finalize) (ValaTestTestCaseAdaptor *self);
};

struct _ValaTestTestCaseAdaptorPrivate {
	gchar* _name;
	ValaTestTestCaseTestMethod test;
	gpointer test_target;
	GDestroyNotify test_target_destroy_notify;
	ValaTestTestCase* test_case;
};

struct _ValaTestTestCaseParamSpecAdaptor {
	GParamSpec parent_instance;
};


static gpointer vala_test_test_case_parent_class = NULL;
static gpointer vala_test_test_case_adaptor_parent_class = NULL;

GType vala_test_test_case_get_type (void) G_GNUC_CONST;
static gpointer vala_test_test_case_adaptor_ref (gpointer instance);
static void vala_test_test_case_adaptor_unref (gpointer instance);
static GParamSpec* vala_test_test_case_param_spec_adaptor (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) G_GNUC_UNUSED;
static void vala_test_test_case_value_set_adaptor (GValue* value, gpointer v_object) G_GNUC_UNUSED;
static void vala_test_test_case_value_take_adaptor (GValue* value, gpointer v_object) G_GNUC_UNUSED;
static gpointer vala_test_test_case_value_get_adaptor (const GValue* value) G_GNUC_UNUSED;
static GType vala_test_test_case_adaptor_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
#define VALA_TEST_TEST_CASE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALA_TEST_TYPE_TEST_CASE, ValaTestTestCasePrivate))
enum  {
	VALA_TEST_TEST_CASE_DUMMY_PROPERTY
};
ValaTestTestCase* vala_test_test_case_construct (GType object_type, const gchar* name);
void vala_test_test_case_add_test (ValaTestTestCase* self, const gchar* name, ValaTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify);
static ValaTestTestCaseAdaptor* vala_test_test_case_adaptor_new (const gchar* name, ValaTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify, ValaTestTestCase* test_case);
static ValaTestTestCaseAdaptor* vala_test_test_case_adaptor_construct (GType object_type, const gchar* name, ValaTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify, ValaTestTestCase* test_case);
static void _vala_array_add1 (ValaTestTestCaseAdaptor*** array, int* length, int* size, ValaTestTestCaseAdaptor* value);
static const gchar* vala_test_test_case_adaptor_get_name (ValaTestTestCaseAdaptor* self);
static void vala_test_test_case_adaptor_set_up (ValaTestTestCaseAdaptor* self, void* fixture);
static void _vala_test_test_case_adaptor_set_up_gtest_fixture_func (void* fixture, gpointer self);
static void vala_test_test_case_adaptor_run (ValaTestTestCaseAdaptor* self, void* fixture);
static void _vala_test_test_case_adaptor_run_gtest_fixture_func (void* fixture, gpointer self);
static void vala_test_test_case_adaptor_tear_down (ValaTestTestCaseAdaptor* self, void* fixture);
static void _vala_test_test_case_adaptor_tear_down_gtest_fixture_func (void* fixture, gpointer self);
void vala_test_test_case_set_up (ValaTestTestCase* self);
static void vala_test_test_case_real_set_up (ValaTestTestCase* self);
void vala_test_test_case_tear_down (ValaTestTestCase* self);
static void vala_test_test_case_real_tear_down (ValaTestTestCase* self);
GTestSuite* vala_test_test_case_get_suite (ValaTestTestCase* self);
#define VALA_TEST_TEST_CASE_ADAPTOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALA_TEST_TEST_CASE_TYPE_ADAPTOR, ValaTestTestCaseAdaptorPrivate))
enum  {
	VALA_TEST_TEST_CASE_ADAPTOR_DUMMY_PROPERTY
};
static void vala_test_test_case_adaptor_set_name (ValaTestTestCaseAdaptor* self, const gchar* value);
static void vala_test_test_case_adaptor_finalize (ValaTestTestCaseAdaptor* obj);
static void vala_test_test_case_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


ValaTestTestCase* vala_test_test_case_construct (GType object_type, const gchar* name) {
	ValaTestTestCase * self = NULL;
	const gchar* _tmp0_;
	GTestSuite* _tmp1_;
	g_return_val_if_fail (name != NULL, NULL);
	self = (ValaTestTestCase*) g_object_new (object_type, NULL);
	_tmp0_ = name;
	_tmp1_ = g_test_create_suite (_tmp0_);
	self->priv->suite = _tmp1_;
	return self;
}


static gpointer _vala_test_test_case_adaptor_ref0 (gpointer self) {
	return self ? vala_test_test_case_adaptor_ref (self) : NULL;
}


static void _vala_array_add1 (ValaTestTestCaseAdaptor*** array, int* length, int* size, ValaTestTestCaseAdaptor* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (ValaTestTestCaseAdaptor*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_test_test_case_adaptor_set_up_gtest_fixture_func (void* fixture, gpointer self) {
	vala_test_test_case_adaptor_set_up (self, fixture);
}


static void _vala_test_test_case_adaptor_run_gtest_fixture_func (void* fixture, gpointer self) {
	vala_test_test_case_adaptor_run (self, fixture);
}


static void _vala_test_test_case_adaptor_tear_down_gtest_fixture_func (void* fixture, gpointer self) {
	vala_test_test_case_adaptor_tear_down (self, fixture);
}


void vala_test_test_case_add_test (ValaTestTestCase* self, const gchar* name, ValaTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify) {
	const gchar* _tmp0_;
	ValaTestTestCaseTestMethod _tmp1_;
	void* _tmp1__target;
	GDestroyNotify _tmp1__target_destroy_notify;
	ValaTestTestCaseAdaptor* _tmp2_;
	ValaTestTestCaseAdaptor* adaptor;
	ValaTestTestCaseAdaptor** _tmp3_;
	gint _tmp3__length1;
	ValaTestTestCaseAdaptor* _tmp4_;
	GTestSuite* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	GTestCase* _tmp8_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = name;
	_tmp1_ = test;
	_tmp1__target = test_target;
	_tmp1__target_destroy_notify = test_target_destroy_notify;
	test_target_destroy_notify = NULL;
	_tmp2_ = vala_test_test_case_adaptor_new (_tmp0_, _tmp1_, _tmp1__target, _tmp1__target_destroy_notify, self);
	adaptor = _tmp2_;
	_tmp3_ = self->priv->adaptors;
	_tmp3__length1 = self->priv->adaptors_length1;
	_tmp4_ = _vala_test_test_case_adaptor_ref0 (adaptor);
	_vala_array_add1 (&self->priv->adaptors, &self->priv->adaptors_length1, &self->priv->_adaptors_size_, _tmp4_);
	_tmp5_ = self->priv->suite;
	_tmp6_ = vala_test_test_case_adaptor_get_name (adaptor);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_test_create_case (_tmp7_, (gsize) 0, adaptor, _vala_test_test_case_adaptor_set_up_gtest_fixture_func, _vala_test_test_case_adaptor_run_gtest_fixture_func, _vala_test_test_case_adaptor_tear_down_gtest_fixture_func);
	g_test_suite_add (_tmp5_, _tmp8_);
	_vala_test_test_case_adaptor_unref0 (adaptor);
	(test_target_destroy_notify == NULL) ? NULL : (test_target_destroy_notify (test_target), NULL);
	test = NULL;
	test_target = NULL;
	test_target_destroy_notify = NULL;
}


static void vala_test_test_case_real_set_up (ValaTestTestCase* self) {
}


void vala_test_test_case_set_up (ValaTestTestCase* self) {
	g_return_if_fail (self != NULL);
	VALA_TEST_TEST_CASE_GET_CLASS (self)->set_up (self);
}


static void vala_test_test_case_real_tear_down (ValaTestTestCase* self) {
}


void vala_test_test_case_tear_down (ValaTestTestCase* self) {
	g_return_if_fail (self != NULL);
	VALA_TEST_TEST_CASE_GET_CLASS (self)->tear_down (self);
}


GTestSuite* vala_test_test_case_get_suite (ValaTestTestCase* self) {
	GTestSuite* result = NULL;
	GTestSuite* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->suite;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static ValaTestTestCaseAdaptor* vala_test_test_case_adaptor_construct (GType object_type, const gchar* name, ValaTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify, ValaTestTestCase* test_case) {
	ValaTestTestCaseAdaptor* self = NULL;
	const gchar* _tmp0_;
	ValaTestTestCaseTestMethod _tmp1_;
	void* _tmp1__target;
	GDestroyNotify _tmp1__target_destroy_notify;
	ValaTestTestCase* _tmp2_;
	ValaTestTestCase* _tmp3_;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (test_case != NULL, NULL);
	self = (ValaTestTestCaseAdaptor*) g_type_create_instance (object_type);
	_tmp0_ = name;
	vala_test_test_case_adaptor_set_name (self, _tmp0_);
	_tmp1_ = test;
	_tmp1__target = test_target;
	_tmp1__target_destroy_notify = test_target_destroy_notify;
	test_target_destroy_notify = NULL;
	(self->priv->test_target_destroy_notify == NULL) ? NULL : (self->priv->test_target_destroy_notify (self->priv->test_target), NULL);
	self->priv->test = NULL;
	self->priv->test_target = NULL;
	self->priv->test_target_destroy_notify = NULL;
	self->priv->test = _tmp1_;
	self->priv->test_target = _tmp1__target;
	self->priv->test_target_destroy_notify = _tmp1__target_destroy_notify;
	_tmp2_ = test_case;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 (self->priv->test_case);
	self->priv->test_case = _tmp3_;
	(test_target_destroy_notify == NULL) ? NULL : (test_target_destroy_notify (test_target), NULL);
	test = NULL;
	test_target = NULL;
	test_target_destroy_notify = NULL;
	return self;
}


static ValaTestTestCaseAdaptor* vala_test_test_case_adaptor_new (const gchar* name, ValaTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify, ValaTestTestCase* test_case) {
	return vala_test_test_case_adaptor_construct (VALA_TEST_TEST_CASE_TYPE_ADAPTOR, name, test, test_target, test_target_destroy_notify, test_case);
}


static void vala_test_test_case_adaptor_set_up (ValaTestTestCaseAdaptor* self, void* fixture) {
	ValaTestTestCase* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->test_case;
	vala_test_test_case_set_up (_tmp0_);
}


static void vala_test_test_case_adaptor_run (ValaTestTestCaseAdaptor* self, void* fixture) {
	ValaTestTestCaseTestMethod _tmp0_;
	void* _tmp0__target;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->test;
	_tmp0__target = self->priv->test_target;
	_tmp0_ (_tmp0__target);
}


static void vala_test_test_case_adaptor_tear_down (ValaTestTestCaseAdaptor* self, void* fixture) {
	ValaTestTestCase* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->test_case;
	vala_test_test_case_tear_down (_tmp0_);
}


static const gchar* vala_test_test_case_adaptor_get_name (ValaTestTestCaseAdaptor* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


static void vala_test_test_case_adaptor_set_name (ValaTestTestCaseAdaptor* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
}


static void vala_test_test_case_value_adaptor_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void vala_test_test_case_value_adaptor_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		vala_test_test_case_adaptor_unref (value->data[0].v_pointer);
	}
}


static void vala_test_test_case_value_adaptor_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = vala_test_test_case_adaptor_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer vala_test_test_case_value_adaptor_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* vala_test_test_case_value_adaptor_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ValaTestTestCaseAdaptor* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = vala_test_test_case_adaptor_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* vala_test_test_case_value_adaptor_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ValaTestTestCaseAdaptor** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = vala_test_test_case_adaptor_ref (value->data[0].v_pointer);
	}
	return NULL;
}


static GParamSpec* vala_test_test_case_param_spec_adaptor (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ValaTestTestCaseParamSpecAdaptor* spec;
	g_return_val_if_fail (g_type_is_a (object_type, VALA_TEST_TEST_CASE_TYPE_ADAPTOR), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


static gpointer vala_test_test_case_value_get_adaptor (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TEST_TEST_CASE_TYPE_ADAPTOR), NULL);
	return value->data[0].v_pointer;
}


static void vala_test_test_case_value_set_adaptor (GValue* value, gpointer v_object) {
	ValaTestTestCaseAdaptor* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TEST_TEST_CASE_TYPE_ADAPTOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALA_TEST_TEST_CASE_TYPE_ADAPTOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		vala_test_test_case_adaptor_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		vala_test_test_case_adaptor_unref (old);
	}
}


static void vala_test_test_case_value_take_adaptor (GValue* value, gpointer v_object) {
	ValaTestTestCaseAdaptor* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALA_TEST_TEST_CASE_TYPE_ADAPTOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALA_TEST_TEST_CASE_TYPE_ADAPTOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		vala_test_test_case_adaptor_unref (old);
	}
}


static void vala_test_test_case_adaptor_class_init (ValaTestTestCaseAdaptorClass * klass) {
	vala_test_test_case_adaptor_parent_class = g_type_class_peek_parent (klass);
	VALA_TEST_TEST_CASE_ADAPTOR_CLASS (klass)->finalize = vala_test_test_case_adaptor_finalize;
	g_type_class_add_private (klass, sizeof (ValaTestTestCaseAdaptorPrivate));
}


static void vala_test_test_case_adaptor_instance_init (ValaTestTestCaseAdaptor * self) {
	self->priv = VALA_TEST_TEST_CASE_ADAPTOR_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void vala_test_test_case_adaptor_finalize (ValaTestTestCaseAdaptor* obj) {
	ValaTestTestCaseAdaptor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_TEST_TEST_CASE_TYPE_ADAPTOR, ValaTestTestCaseAdaptor);
	_g_free0 (self->priv->_name);
	(self->priv->test_target_destroy_notify == NULL) ? NULL : (self->priv->test_target_destroy_notify (self->priv->test_target), NULL);
	self->priv->test = NULL;
	self->priv->test_target = NULL;
	self->priv->test_target_destroy_notify = NULL;
	_g_object_unref0 (self->priv->test_case);
}


static GType vala_test_test_case_adaptor_get_type (void) {
	static volatile gsize vala_test_test_case_adaptor_type_id__volatile = 0;
	if (g_once_init_enter (&vala_test_test_case_adaptor_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { vala_test_test_case_value_adaptor_init, vala_test_test_case_value_adaptor_free_value, vala_test_test_case_value_adaptor_copy_value, vala_test_test_case_value_adaptor_peek_pointer, "p", vala_test_test_case_value_adaptor_collect_value, "p", vala_test_test_case_value_adaptor_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ValaTestTestCaseAdaptorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_test_test_case_adaptor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaTestTestCaseAdaptor), 0, (GInstanceInitFunc) vala_test_test_case_adaptor_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType vala_test_test_case_adaptor_type_id;
		vala_test_test_case_adaptor_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ValaTestTestCaseAdaptor", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&vala_test_test_case_adaptor_type_id__volatile, vala_test_test_case_adaptor_type_id);
	}
	return vala_test_test_case_adaptor_type_id__volatile;
}


static gpointer vala_test_test_case_adaptor_ref (gpointer instance) {
	ValaTestTestCaseAdaptor* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


static void vala_test_test_case_adaptor_unref (gpointer instance) {
	ValaTestTestCaseAdaptor* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		VALA_TEST_TEST_CASE_ADAPTOR_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void vala_test_test_case_class_init (ValaTestTestCaseClass * klass) {
	vala_test_test_case_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ValaTestTestCasePrivate));
	VALA_TEST_TEST_CASE_CLASS (klass)->set_up = vala_test_test_case_real_set_up;
	VALA_TEST_TEST_CASE_CLASS (klass)->tear_down = vala_test_test_case_real_tear_down;
	G_OBJECT_CLASS (klass)->finalize = vala_test_test_case_finalize;
}


static void vala_test_test_case_instance_init (ValaTestTestCase * self) {
	ValaTestTestCaseAdaptor** _tmp0_ = NULL;
	self->priv = VALA_TEST_TEST_CASE_GET_PRIVATE (self);
	_tmp0_ = g_new0 (ValaTestTestCaseAdaptor*, 0 + 1);
	self->priv->adaptors = _tmp0_;
	self->priv->adaptors_length1 = 0;
	self->priv->_adaptors_size_ = self->priv->adaptors_length1;
}


static void vala_test_test_case_finalize (GObject* obj) {
	ValaTestTestCase * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_TEST_TYPE_TEST_CASE, ValaTestTestCase);
	self->priv->adaptors = (_vala_array_free (self->priv->adaptors, self->priv->adaptors_length1, (GDestroyNotify) vala_test_test_case_adaptor_unref), NULL);
	G_OBJECT_CLASS (vala_test_test_case_parent_class)->finalize (obj);
}


GType vala_test_test_case_get_type (void) {
	static volatile gsize vala_test_test_case_type_id__volatile = 0;
	if (g_once_init_enter (&vala_test_test_case_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaTestTestCaseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_test_test_case_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaTestTestCase), 0, (GInstanceInitFunc) vala_test_test_case_instance_init, NULL };
		GType vala_test_test_case_type_id;
		vala_test_test_case_type_id = g_type_register_static (G_TYPE_OBJECT, "ValaTestTestCase", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&vala_test_test_case_type_id__volatile, vala_test_test_case_type_id);
	}
	return vala_test_test_case_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



