# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "Valatest")
set(Valatest_VERSION "0.0.1")
set(required_pkgs
"gio-2.0"
"glib-2.0"
"gobject-2.0"
)
set(srcfiles
"src/valatest-testcase.vala"
"src/valatest.vala"
)
set(vapifiles
"vapi/config.vapi"
)
